//! Swift and Kotlin bindings for the Quakboard sync core, generated by
//! UniFFI. Design: docs/MOBILE_PLAN.md, Phase 2.
//!
//! An app holds one `SyncNode` and implements `SyncDelegate`. This layer only
//! converts types and runs the async runtime; the behaviour is the core's.

use std::{
    fmt,
    path::PathBuf,
    sync::{Arc, Mutex, OnceLock},
};

use quakboard_sync::{
    discovery::short_id,
    protocol::Incompatible,
    service::{SyncHooks, SyncService},
    store::{SyncStore, STORE_FILE_NAME},
    transport::SYNC_PORT,
    ClipPayload,
};
use tokio::{net::TcpListener, runtime::Runtime, task::JoinHandle};

uniffi::setup_scaffolding!();

/// The port desktops listen on. Phones use it too, so desktops reach them.
#[uniffi::export]
pub fn default_sync_port() -> u16 {
    SYNC_PORT
}

#[derive(Debug, uniffi::Error)]
#[uniffi(flat_error)]
pub enum SyncNodeError {
    /// The sync identity in the data folder couldn't be read or saved.
    Storage(String),
    /// The port couldn't be opened, or the runtime couldn't start.
    Network(String),
}

impl fmt::Display for SyncNodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SyncNodeError::Storage(reason) => write!(f, "sync storage failed: {reason}"),
            SyncNodeError::Network(reason) => write!(f, "sync network failed: {reason}"),
        }
    }
}

impl std::error::Error for SyncNodeError {}

#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct DeviceIdentity {
    pub id: String,
    pub name: String,
    /// The "#ab12" other devices show before pairing.
    pub short_id: String,
}

/// Which device needs a newer Quakboard before the two can sync again.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum UpdateNeeded {
    ThisDevice,
    OtherDevice,
}

/// A paired device. Never carries its key.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct PeerInfo {
    pub id: String,
    pub name: String,
    /// Last `ip:port` it was reached at.
    pub last_addr: Option<String>,
    /// Set while its frames are refused as incompatible; not saved.
    pub update_needed: Option<UpdateNeeded>,
}

/// What the app does when something arrives. Called on a background thread;
/// hop to the main thread before touching UI.
#[uniffi::export(with_foreign)]
pub trait SyncDelegate: Send + Sync {
    /// Text a paired device sent.
    fn on_text(&self, text: String);
}

#[derive(uniffi::Object)]
pub struct SyncNode {
    service: Arc<SyncService>,
    listen_port: u16,
    listener: Mutex<Option<JoinHandle<()>>>,
}

#[uniffi::export]
impl SyncNode {
    /// Open this device's sync identity in `data_dir`, creating it on first
    /// run with `device_name`. Later runs keep the stored name.
    #[uniffi::constructor]
    pub fn new(
        data_dir: String,
        device_name: String,
        listen_port: u16,
        delegate: Arc<dyn SyncDelegate>,
    ) -> Result<Arc<Self>, SyncNodeError> {
        let store_path = PathBuf::from(data_dir).join(STORE_FILE_NAME);
        let store = if store_path.exists() {
            SyncStore::load_or_create(&store_path)
        } else {
            let store = SyncStore::new(device_name);
            store.save(&store_path).map(|()| store)
        }
        .map_err(|e| SyncNodeError::Storage(e.to_string()))?;

        let service = SyncService::new(store, store_path, listen_port, hooks(delegate));
        Ok(Arc::new(SyncNode {
            service,
            listen_port,
            listener: Mutex::new(None),
        }))
    }

    /// Start receiving from paired devices. Does nothing if already started.
    pub async fn start(&self) -> Result<(), SyncNodeError> {
        if lock(&self.listener).is_some() {
            return Ok(());
        }
        let port = self.listen_port;
        let listener = runtime()?
            .spawn(async move { TcpListener::bind(("0.0.0.0", port)).await })
            .await
            .map_err(|e| SyncNodeError::Network(e.to_string()))?
            .map_err(|e| SyncNodeError::Network(format!("could not listen on {port}: {e}")))?;

        let mut running = lock(&self.listener);
        // Another start() may have won while this one was binding.
        if running.is_none() {
            *running = Some(runtime()?.spawn(self.service.clone().listen(listener)));
        }
        Ok(())
    }

    /// Stop receiving. Sending still works.
    pub fn stop(&self) {
        if let Some(listener) = lock(&self.listener).take() {
            listener.abort();
        }
    }

    pub fn identity(&self) -> DeviceIdentity {
        let (id, name) = self.service.identity();
        DeviceIdentity {
            short_id: short_id(&id).to_string(),
            id,
            name,
        }
    }

    pub fn peers(&self) -> Vec<PeerInfo> {
        self.service
            .peers()
            .into_iter()
            .map(|peer| PeerInfo {
                update_needed: self.service.incompatibility(&peer.id).map(
                    |refusal| match refusal {
                        Incompatible::ThisTooOld => UpdateNeeded::ThisDevice,
                        Incompatible::PeerTooOld => UpdateNeeded::OtherDevice,
                    },
                ),
                id: peer.id,
                name: peer.name,
                last_addr: peer.last_addr,
            })
            .collect()
    }

    /// Send text to every paired device. Returns how many it reached.
    pub async fn send_text(&self, text: String) -> u32 {
        let Ok(runtime) = runtime() else {
            return 0;
        };
        let service = self.service.clone();
        let clip = ClipPayload {
            text,
            content_type: "text".into(),
        };
        let reached = runtime
            .spawn(async move { service.send_clip(clip).await })
            .await
            .unwrap_or(0);
        u32::try_from(reached).unwrap_or(u32::MAX)
    }
}

impl Drop for SyncNode {
    fn drop(&mut self) {
        self.stop();
    }
}

fn hooks(delegate: Arc<dyn SyncDelegate>) -> SyncHooks {
    // NOTE: images, file offers, pairing events and the nearby-device lookup
    // are wired in the next pass of Phase 2, step 3.
    SyncHooks {
        apply_clip: Arc::new(move |clip| delegate.on_text(clip.text)),
        apply_image: Arc::new(|_| {}),
        apply_offer: Arc::new(|_| {}),
        lookup_offer: Arc::new(|_| None),
        on_pairing: Arc::new(|_| {}),
        resolve_addr: Arc::new(|_| None),
    }
}

/// One runtime for every node in the process, so a node can be dropped from
/// any thread (dropping a runtime inside async code panics).
fn runtime() -> Result<&'static Runtime, SyncNodeError> {
    static RUNTIME: OnceLock<Result<Runtime, String>> = OnceLock::new();
    RUNTIME
        .get_or_init(|| Runtime::new().map_err(|e| e.to_string()))
        .as_ref()
        .map_err(|e| SyncNodeError::Network(format!("could not start the sync runtime: {e}")))
}

/// A poisoned lock only means another thread panicked mid-update; the data is
/// still usable.
fn lock<T>(mutex: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    mutex
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use quakboard_sync::store::Peer;
    use tokio::sync::mpsc;

    use super::*;

    const A_ID: &str = "11111111-1111-4111-8111-111111111111";
    const B_ID: &str = "22222222-2222-4222-8222-222222222222";

    /// A delegate that collects what arrives, as an app would show it.
    struct Inbox(mpsc::UnboundedSender<String>);

    impl SyncDelegate for Inbox {
        fn on_text(&self, text: String) {
            let _ = self.0.send(text);
        }
    }

    struct Device {
        node: Arc<SyncNode>,
        texts: mpsc::UnboundedReceiver<String>,
        dir: tempfile::TempDir,
    }

    fn free_port() -> u16 {
        let probe = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        probe.local_addr().unwrap().port()
    }

    fn open(dir: tempfile::TempDir, name: &str, port: u16) -> Device {
        let (tx, texts) = mpsc::unbounded_channel();
        let data_dir = dir.path().to_string_lossy().to_string();
        let node = SyncNode::new(data_dir, name.into(), port, Arc::new(Inbox(tx))).unwrap();
        Device { node, texts, dir }
    }

    /// A store as a past pairing with `peer_id` at `peer_port` left it.
    fn paired_store(id: &str, peer_id: &str, peer_port: u16) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let store = SyncStore {
            device_id: id.into(),
            device_name: format!("{id} name"),
            peers: vec![Peer {
                id: peer_id.into(),
                name: "Laptop".into(),
                key: [9; 32],
                last_addr: Some(format!("127.0.0.1:{peer_port}")),
            }],
        };
        store.save(&dir.path().join(STORE_FILE_NAME)).unwrap();
        dir
    }

    async fn paired_devices() -> (Device, Device) {
        let (port_a, port_b) = (free_port(), free_port());
        let a = open(paired_store(A_ID, B_ID, port_b), "a", port_a);
        let b = open(paired_store(B_ID, A_ID, port_a), "b", port_b);
        a.node.start().await.unwrap();
        b.node.start().await.unwrap();
        (a, b)
    }

    async fn next_text(device: &mut Device) -> Option<String> {
        tokio::time::timeout(Duration::from_secs(2), device.texts.recv())
            .await
            .ok()
            .flatten()
    }

    #[tokio::test]
    async fn text_sent_by_one_node_arrives_at_the_other() {
        let (a, mut b) = paired_devices().await;
        a.node.send_text("hello phone".into()).await;

        assert_eq!(next_text(&mut b).await.as_deref(), Some("hello phone"));
    }

    #[tokio::test]
    async fn send_text_reports_the_devices_it_reached() {
        let (a, _b) = paired_devices().await;
        assert_eq!(a.node.send_text("hello".into()).await, 1);
    }

    #[tokio::test]
    async fn text_that_just_arrived_can_be_sent_back() {
        // Phones only send on purpose, so there's no echo guard to swallow it.
        let (a, mut b) = paired_devices().await;
        a.node.send_text("ping".into()).await;
        next_text(&mut b).await;

        assert_eq!(b.node.send_text("ping".into()).await, 1);
    }

    #[tokio::test]
    async fn stopped_node_receives_nothing() {
        let (a, b) = paired_devices().await;
        b.node.stop();

        assert_eq!(a.node.send_text("anyone?".into()).await, 0);
    }

    #[test]
    fn first_run_uses_the_given_device_name() {
        let device = open(tempfile::tempdir().unwrap(), "Dereck's iPhone", free_port());
        assert_eq!(device.node.identity().name, "Dereck's iPhone");
    }

    #[test]
    fn later_runs_keep_the_stored_identity() {
        let first = open(tempfile::tempdir().unwrap(), "iPhone", free_port());
        let before = first.node.identity();
        let again = open(first.dir, "Renamed", free_port());

        assert_eq!(again.node.identity(), before);
    }

    #[test]
    fn paired_devices_are_listed() {
        let device = open(paired_store(A_ID, B_ID, 4000), "a", free_port());
        assert_eq!(
            device.node.peers(),
            vec![PeerInfo {
                id: B_ID.into(),
                name: "Laptop".into(),
                last_addr: Some("127.0.0.1:4000".into()),
                update_needed: None,
            }]
        );
    }

    #[test]
    fn short_id_is_the_last_four_characters_of_the_id() {
        let device = open(paired_store(A_ID, B_ID, 4000), "a", free_port());
        assert_eq!(device.node.identity().short_id, "1111");
    }
}
