// swift-tools-version:5.9
// The XCFramework and Sources/ are generated by scripts/build-ios.sh.
import PackageDescription

let package = Package(
    name: "QuakboardSync",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "QuakboardSync", targets: ["QuakboardSync"]),
    ],
    targets: [
        .binaryTarget(name: "QuakboardSyncFFI", path: "QuakboardSyncFFI.xcframework"),
        .target(name: "QuakboardSync", dependencies: ["QuakboardSyncFFI"]),
    ]
)
